#ifndef SYSTRAYLAUNCHER_VERSION_H
#define SYSTRAYLAUNCHER_VERSION_H

#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 0
#define APP_VERSION_PATCH 22
#define APP_VERSION_BUILD 0

#define APP_DISPLAY_NAME_STRING "System Tray Launcher"
#define APP_DISPLAY_NAME_WSTRING L"System Tray Launcher"

#define APP_VERSION_RESOURCE 1,0,22,0
#define APP_VERSION_STRING "1.0.22"
#define APP_FILE_VERSION_STRING "1.0.22.0"
#define APP_VERSION_WSTRING L"1.0.22"

#endif
